[package]
name = "mydns"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]

[dependencies]
tokio = "*"
futures = "*"
trust-dns = "*"
trust-dns-server = "*"
trust-dns-resolver = "*"
trust-dns-proto = "*"
log = "*"
pretty_env_logger = "*"
